export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
        {children}
        <footer>
            <p>Footer</p>
            <ul>
                <li>About</li>
                <li>Contact</li>
                <li>Privacy Policy</li>
            </ul>
        </footer>

      </body>
    </html>
  )
}
