export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
        <header>
            <h1>Product Layout</h1>
            <nav justify-content="space-between">
                <ul>
                <li>Home</li>
                <li>Products</li>
                <li>Contact</li>
                </ul>
            </nav>
        </header>
      <body>{children}</body>
    </html>
  )
}
